app/chat/__init__.py
from flask import Blueprint

bp = Blueprint('chat', __name__)

from app.chat import routes

app/chat/routes.py
from flask import render_template, redirect, url_for, current_app, flash, jsonify, json, request, make_response, session
from flask_login import login_user, logout_user, current_user, login_required
from flask_socketio import join_room, leave_room, send, SocketIO, emit, rooms
from datetime import datetime
import functools

from app.models import User, Message, ActiveRoom
from app import socketio, db
from app.chat import bp
from app.define.query import return_messages


def authenticated_only(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        if not current_user.is_authenticated:
            disconnect()
        else:
            return f(*args, **kwargs)

    return wrapped




# @bp.before_request
# def before_request():
#     if current_user.is_authenticated and current_user.is_user():
#         if not ActiveRoom.is_exists():
#             new_room = ActiveRoom(room=current_user.room, active_users=1)
#             db.session.add(new_room)
#             db.session.commit()


@bp.route('/messenger', methods=['GET', 'POST'])
@login_required
def messenger():
    if current_user:
        room = current_user.room
        if request.method == 'GET':
            return render_template('chat/messenger.html', code=room)
        if request.method == 'POST':
            # if not session.modified:
            #     session.modified = True
            data = Message.get_messages(room)
            response = make_response(data)
            response.headers['User-InfoName'] = current_user.username
            return response


@bp.route('/operator_room', methods=['GET', 'POST'])
@login_required
def operator_room():
    if current_user.is_admin():
        users_rooms = ActiveRoom.query.all()
        return render_template('chat/operator_room.html', users_rooms=users_rooms)
    return render_template('index.html', flash='Вход запрещён!')




@bp.route('/operator_messenger/<room_name>', methods=['GET', 'POST'])
@login_required
def operator_joinroom(room_name):
    if current_user.is_admin():
        current_user.room = room_name
        room = ActiveRoom.query.filter_by(room=current_user.room).first()
        room.active_users = 2
        db.session.commit()
        return render_template('chat/messenger.html', code=f'Оператор в комнате {current_user.room}')
    return render_template('index.html', flash='Вход запрещён!')


#
#
#
#

@socketio.on("connect")
@authenticated_only
def connect():
    test = request.sid
    print(current_user, 'Подключился', test)
    room = current_user.room
    name = current_user.username
    time = datetime.utcnow().isoformat()
    join_room(room)
    if current_user.is_user():
        print(current_user.is_user())
        if not ActiveRoom.is_exists():
            print(ActiveRoom.is_exists())
            new_room = ActiveRoom(room=current_user.room, active_users=1, new_messages=0)
            db.session.add(new_room)
            db.session.commit()
    if current_user.is_admin():
        emit('connect', {'name': name, 'message': 'подключился к чату', 'timestamp': time}, to=room)



@socketio.on("disconnect")
@authenticated_only
def disconnect():
    print(current_user, 'Отключился')
    room = current_user.room
    name = current_user.username
    time = datetime.utcnow().isoformat()
    leave_room(room)
    active_room = ActiveRoom.query.filter_by(room=room).first()
    if current_user.is_admin():
        active_room.active_users = 1
        emit('disconnect', {'name': name, 'message': 'покинул чату', 'timestamp': time}, to=room)
    if current_user.is_user() and active_room.new_messages == 0:
        ActiveRoom.query.filter_by(room=room).delete()
    db.session.commit()


#
#
@socketio.on("message")
@authenticated_only
def message(data):
    room = current_user.room
    time = datetime.utcnow().isoformat()
    content = {
        "name": current_user.username,
        "message": data["data"],
        "timestamp": time
    }
    print(content)
    send(content, to=room)
    message = Message(name=current_user.username, message=data["data"], room=room)
    get_room = ActiveRoom.query.filter_by(room=room).first()
    if current_user.is_user():
        if get_room.active_users == 1:
            get_room.new_messages += 1
        db.session.add(get_room)
    if current_user.is_admin():
        get_room.active_users = 2
        get_room.new_messages = 0
    db.session.add(message)
    db.session.commit()

app/templates/chat/adm_messenger.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/chat/messenger.html
{% extends "base.html" %}

{% block chat %}
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.js') }}"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

        <main role="main" class="col-md-12">
          <div class="pt-3 pb-2 mb-3 border-bottom text-center chat-head" >
            <h1 class="h2 text-center">Чат МРГ Воронеж</h1>
          </div>
            </main>
<div class="panel messages-panel">
    <div class="chat-body" id="messageFeed"></div>
    <div class="chat-footer">
      <div class="input-group mb-3">
        <input type="text" class="form-control" id="message">
        <div class="input-group-append">
         <button class="btn btn-outline-secondary send-message-button btn-info" type="submit" id="messageBtn"  onClick="sendMessage()">Отправить<i class="fa fa-send fly"></i></button>

        </div>
      </div>
    </div>
</div>
<!--    <div class="chat-footer"><textarea class="send-message-text">-->

<!--    </textarea><label class="upload-file">-->
<!--        <input type="file" id="message" required=""> <i class="fa fa-paperclip"></i> </label>-->
<!--        <button type="button" class="send-message-button btn-info" onClick="sendMessage()"> <i class="fa fa-send"></i> </button>-->




<!--    <div class="container-fluid">-->
<!--      <div class="row">-->
<!--        <main role="main" class="col-md-12">-->
<!--          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">-->
<!--            <h1 class="h2">Bootstrap Chat</h1>-->
<!--          </div>-->
<!--            <ul class="list-unstyled text-break" id="messageFeed">-->
<!--            </ul>-->
<!--           <div class="input-group mb-3">-->
<!--            <input type="text" class="form-control" id="messageTextarea">-->
<!--            <div class="input-group-append">-->
<!--              <button class="btn btn-outline-secondary" type="button" id="send">Send</button>-->
<!--            </div>-->
<!--          </div>-->
<!--        </main>-->
<!--      </div>-->
<!--    </div>-->


        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
<!--      Добавить integrity !!!! Обязательно!-->
<!--        <link type="text/javascript" href="{{ url_for('static', filename='js/socket.io.js', _external=True) }}">-->
        <script type="text/javascript" src="{{ url_for('static', filename='js/sockets.js') }}"></script>

{% endblock %}

app/templates/chat/messenger2.html
{% extends "base.html" %}

{% block chat %}
<div class="message-box">
  <h2>Chat Room: {{code}}</h2>
  <div class="messages" id="messages"></div>
  <div class="inputs">
    <input
      type="text"
      rows="3"
      placeholder="Message"
      name="message"
      id="message"
    />
    <button type="button" name="send" id="send-btn" onClick="sendMessage()">
      Send
    </button>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
<script type="text/javascript">
  var socketio = io();

  const messages = document.getElementById("messages");

  const createMessage = (name, msg) => {
    const content = `
    <div class="text">
        <span>
            <strong>${name}</strong>: ${msg}
        </span>
        <span class="muted">
            ${new Date().toLocaleString()}
        </span>
    </div>
    `;
    messages.innerHTML += content;
    messages.scrollTop = messages.scrollHeight - messages.clientHeight;
  };

  socketio.on("message", (data) => {
    createMessage(data.name, data.message);
  });

  const sendMessage = () => {
    const message = document.getElementById("message");
    if (message.value == "") return;
    socketio.emit("message", { data: message.value });
    message.value = "";
  };
</script>


{% for msg in messages %}

<script type="text/javascript">
  createMessage("{{msg.name}}", "{{msg.message}}");
</script>
{% endfor %}

{% endblock %}

app/templates/chat/operator_messenger.html
{% extends "base.html" %}

{% block chat %}
<div class="message-box">
  <h2>Chat Room: {{code}}</h2>
  <h1>user_rooms</h1>
  {% for room in user_rooms %}
    <h1>{{room}}</h1>
  {% endfor %}
  <div class="messages" id="messages"></div>
  <div class="inputs">
    <input
      type="text"
      rows="3"
      placeholder="Message"
      name="message"
      id="message"
    />
    <button type="button" name="send" id="send-btn" onClick="sendMessage()">
      Send
    </button>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
<script type="text/javascript">
  var socketio = io();

  const messages = document.getElementById("messages");

  const createMessage = (name, msg) => {
    const content = `
    <div class="text">
        <span>
            <strong>${name}</strong>: ${msg}
        </span>
        <span class="muted">
            ${new Date().toLocaleString()}
        </span>
    </div>
    `;
    messages.innerHTML += content;
  };

  socketio.on("message", (data) => {
    createMessage(data.name, data.message);
  });

  const sendMessage = () => {
    const message = document.getElementById("message");
    if (message.value == "") return;
    socketio.emit("message", { data: message.value });
    message.value = "";
  };
</script>
{% for msg in messages %}

<script type="text/javascript">
  createMessage("{{msg.name}}", "{{msg.message}}");
</script>
{% endfor %}
{% endblock %}

app/templates/chat/operator_room.html
{% extends "base.html" %}
{% from 'bootstrap5/table.html' import render_table %}



{% block operator_room %}
    <div class="row">
        <div class="row justify-content-center" >
            <div class="col-md-12 justify-content-center">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Зайти в комнату</th>
                      <th scope="col">Номер комнаты</th>
                        <th scope="col">Дата создания комнаты</th>
                      <th scope="col">Количество новых сообщений</th>
                      <th scope="col">Количество людей в комнате</th>
                    </tr>
                  </thead>
                    <tbody>
                {% for room in users_rooms %}
                    <tr>
                      <th scope="row">1</th>
                      <td><a href="{{ url_for('chat.operator_joinroom', room_name=room.room) }}">Войти в комнату</a></td>
                      <td>{{ room.room }}</td>
                      <td>{{ room.timestamp }}</td>
                      <td>{{ room.new_messages }}</td>
                      <td>{{ room.active_users }}</td>
                    </tr>
                {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}